### ISSUE TITLE
No option to turn off SVG formatting entirely

### ISSUE THREAD

**Issue by craxal** [lishu/vscode-svg#10]
Frankly, I don't like any of the formatting options this extension provides; it completely mangles my files into something much less readable. Unfortunately, I can't just turn it off. There's a setting for switching off the plugins, but some formatting still appears to happen when I save (with format-on-save turned on).

**Comment by lishu** [comment]
[EN (Google Translate)] I'm sorry. This issue cannot be corrected in the short term. I has check the vscode api document.
Formatting on save is invoked by vscode and there are no parameters to know if this action occurs during the save period.

[CN] 我很抱歉这个问题无法在短期修正。我已经查看了 vscode api 文档。
保存时格式化由 vscode 调用并且没有参数可以判断此操作是在保存时发生。

**Comment by lishu** [comment]
[EN (Google Translate)] The experimental setup svg.disableFormatOnSave has been added, because of the api limitation, using an indirect way implementation. Turning on this option may have a negative effect.

[CN] 已经加入了实验性设置  svg.disableFormatOnSave ，因为 api 限制，使用了非直接方式实现。打开此选项可能出现负面影响。

**Comment by gilmoreorless** [comment]
I had the same problem. My workaround was to add this to my VSCode settings:

```js
  "settings": {
    "editor.formatOnSave": true,
    "[svg]": {
      "editor.formatOnSave": false
    }
  }
```

**Comment by craxal** [comment]
Which begs the question: why was this issue closed?

**Comment by lishu** [comment]
I don't quite understand, “svg.disableFormatOnSave” option didn't solve your problem?
