### ISSUE TITLE
svg File content disappears on formatting

### ISSUE THREAD

**Issue by dermoench42** [lishu/vscode-svg#12]
I love coding svg directly with vscode. I like the code formatting abilities 'on save'.

Unfortunaltely I found that on some circumstances the file content disappears on format/save. Editor and File are empty. This can be reverted [ctrl] [z] but it is annoying.

Some reasons for disappearing:

- The content is erroneous, e.g. missing close tag,
- Some xmlns declarations are missing
- A bitmap image inside.

For now I turned of 'format on save' but I suggest the behavoiur of other formatters:

- keep the editor text if something on formatting goes wrong, just display a little notice even if the reason is not available.

Thanks in advance.

ervin

P.S. This might also be related to some other svg plugins, therefore I mention them: 
- svgo
- svg Editor

**Comment by lishu** [comment]
Thank you for your feedback!
Fixed at 0.1.1 Version, Update it & Enjoy
