### ISSUE TITLE
Add zoom support to the preview

### ISSUE THREAD

**Issue by eamodio** [lishu/vscode-svg#15]
It would be great to be able to zoom in on the preview image. It would also be great if there was an option to auto-zoom when previewing small images.

**Comment by lishu** [comment]
Thanks for report
Done in version 0.1.3

**Comment by lishu** [comment]
How auto-zoom action?

**Comment by eamodio** [comment]
It might be less important with the new zoom options -- though I think it would be nice if when I zoomed in on one image, the zoom stayed while that preview tab is open even if I change files.

**Comment by lishu** [comment]
Remember the scaling of each file?

**Comment by eamodio** [comment]
More like remember the scaling of the preview tab itself -- like if I close it and re-open it will go back to 100%, but if I zoom in on one file to 150% and then switch to another file keep it at 150%

**Comment by lishu** [comment]
Thanks for report
Done in version 0.1.4
