### ISSUE TITLE
无法找到键xxx的消息

### ISSUE THREAD

**Issue by lrh3321** [lishu/vscode-svg#3]
![snipaste20170323_170828](https://cloud.githubusercontent.com/assets/2217024/24240097/6311bede-0feb-11e7-9a4b-ce4b815fbef3.png)

平常不会触发，调试插件的时候总是报这个，看着好烦啊。

**Comment by lishu** [comment]
明白了，这是合并了@LaurentTreguier 提供的更新后出现的。但因为这个影响的用户量有限，只为它更新版本让所有人都重新下载好像有点不地道的样子，只能抱歉的说你再忍忍，等下个升级更新时一起解决了。

**Comment by lrh3321** [comment]
其实我已经暂时把它移到 %userprofile%/vscode/extensions 外面去了，需要的时候再移回去。

用这个插件预览会动的SVG还是挺HI的

**Comment by lishu** [comment]
In the 0.0.7 version to solve
