### ISSUE TITLE
SVG Preview background

### ISSUE THREAD

**Issue by ramonakira** [lishu/vscode-svg#4]
Hi,

Would it be possible to change the SVG Preview tab to have a white/gray background (like this https://vignette2.wikia.nocookie.net/tome-of-the-sun/images/5/57/Transparent_Background.png/revision/latest/scale-to-width-down/640?cb=20160121033835)so that white SVG's can be shown?

Thanks in advance!

**Comment by lishu** [comment]
This requirement has been recorded and will be updated recently.

**Comment by lishu** [comment]
In the 0.0.7 version to solve
