### ISSUE TITLE
Destructive Format Document (SVGO)

### ISSUE THREAD

**Issue by myfonj** [lishu/vscode-svg#5]
Integration of SVGO features is really great idea, but binding it as default format provider [1] for SVG syntax seems quite unfortunate to me and might be even dangerous: for example it removes (locally) unused `symbol`s, <del>removes comments</del> and generally alters source far more than plain "Format Document" should. For example document

``` xml
<svg 
	xmlns="http://www.w3.org/2000/svg" 
	xmlns:xlink="http://www.w3.org/1999/xlink">
	<defs>
		<symbol id="a" viewBox="0 0 32 32">
			<circle r="10"/>
		</symbol>
	</defs>
	<!--
		<use xlink:href="#a"/>
	-->
</svg>
```
after formatting with the default confing becomes:  
``` xml
<svg xmlns="http://www.w3.org/2000/svg">
<!--<use xlink:href="#a"/>-->
</svg>
```
what does not seem right. (To get "proper" outcome now one must switch syntax to XML, then invoke "Format document" and switch back.)

I think that only alterations expected from the "Format document" command are indents and line breaks. Not optimizations.

From a quick glance at .svgo.yml [2] it seems that there should be disabled far more plugins in [1] to get simple white-space-wise formatted output. (Perhaps.)

So I'd suggest exporting current formatting / optimizing functionality to a new command and simplify the one used for (expected) simple white space format.

[1] https://github.com/lishu/vscode-svg/blob/master/src/features/svgFormattingProvider.ts
[2] https://github.com/svg/svgo/blob/master/.svgo.yml

**Comment by LaurentTreguier** [comment]
I originally made the PR to introduce SVGO formatting... I should have simply made the entire plugin configuration available in the extension settings, with everything disabled by default ; that should avoid this kind of trouble.

**Comment by LaurentTreguier** [comment]
I have a working version of the extension that desactivates all plugins by default, your SVG becomes this:
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <symbol id="a" viewBox="0 0 32 32">
            <circle r="10"/>
        </symbol>
    </defs>
<!--<use xlink:href="#a"/>-->
</svg>
```
I'm thinking of keeping `sortAttrs` activated by default, as it's the only one that's really about formatting and doesn't remove or transform anything.

**Comment by LaurentTreguier** [comment]
I made a new PR (#6) that changes config to disable all plugins (except `sortAttrs`) by default, and that provides a single object to be able to configure every plugin instead of being restricted to the few I had deemed harmful before.
